# platform = multi_platform_ol,multi_platform_sle
# reboot = true
# strategy = patch
# complexity = low
# disruption = high
- name: "Security patches are up to date"
  package:
    name: "*"
    state: "latest"
  tags:
    - skip_ansible_lint # [ANSIBLE0010] Skipping lint because ANSIBLE0010 is a bad security practice
